### PR TITLE
Updated for 3.18 with patch from andrwmorph

### PR DESCRIPTION
**Pull request by wackywendell**
See the AUR thread for details.

### CODE REVIEW

**Comment by davispuh** [comment]
Thanks :) , sorry it took so long. Just tested and works fine, will update package on AUR soon.

**Comment by wackywendell** [comment]
No problem! And thanks for maintaining the AUR package! I wouldn't even know where to begin without all you've started... thanks!

**Comment by andrwmorph** [comment]
Thanks for creating the pull request Wendell (and thanks to Davispuh for the AUR package)! I would have done it myself but I was worried that I put the patches in the wrong file.

**Comment by wackywendell** [comment]
No problem! And I probably have less idea what I'm doing than either of you, but I figured that if I'd done it wrong, its all open-source and someone could correct me...

**Pull request merged**
