### PR TITLE
Adopted change to BDI patch in rasa's repository.

### PR DESCRIPTION
**Pull request by lotan**

### CODE REVIEW

**Comment by davispuh** [comment]
Thanks :) Sorry for taking so long but I don't use this anymore... Anyway I now fixed it for v4.1 and will push to AUR

**Comment by lotan** [comment]
That's absolutely fine. This doesn't work with gcc 5 anyway.
I had seen your note on AUR.
I'm using fuse hgfs now, so I'm not depending on this either anymore.

**Comment by davispuh** [comment]
No, it does work fine with GCC 5.2 on Linux 4.1, I just tested it :)

**Comment by lotan** [comment]
Really? That's cool :)
But not so needed anymore, I'll stick to fuse hgfs.
Thanks for the info!

**Pull request merged**
